### ISSUE TITLE
Porter: Information for your profile is missing.

### ISSUE THREAD

**Issue by LukasBuecherl** [fluentverification/FLUENT-Website#10]
@PorterGiles123: Your profile is still empty. I'm not sure if you were there when I gave an introduction but if you need help let me know and we can set up a 15 min meeting to go over everything.

**Comment by PorterGiles123** [comment]
@LukasBuecherl, which profile are you referring to?

**Comment by LukasBuecherl** [comment]
Your profile on our new website is missing a bio, education, interests, and picture. The website is hosted on GitHub, in the repository I opened this issue. We can talk about it on Friday and then set up a 15 min meeting so I can show you how to add that information.
